services:
    _defaults:
        public: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    codefog_news_categories.listener.change_language:
        class: Codefog\NewsCategoriesBundle\EventListener\ChangeLanguageListener
        arguments:
            - "@codefog_news_categories.manager"
        tags:
            - { name: contao.hook, hook: changelanguageNavigation, method: onChangeLanguageNavigation }

    codefog_news_categories.listener.insert_tags:
        class: Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener
        arguments:
            - "@codefog_news_categories.manager"
        tags:
            - { name: contao.hook, hook: replaceInsertTags, method: onReplace }

    codefog_news_categories.listener.news:
        class: Codefog\NewsCategoriesBundle\EventListener\NewsListener
        arguments:
            - "@codefog_news_categories.news_criteria_builder"
        tags:
            - { name: contao.hook, hook: newsListCountItems, method: onNewsListCountItems }
            - { name: contao.hook, hook: newsListFetchItems, method: onNewsListFetchItems }

    codefog_news_categories.listener.news_feed:
        class: Codefog\NewsCategoriesBundle\EventListener\NewsFeedListener
        arguments:
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: Contao\NewsBundle\Event\FetchArticlesForFeedEvent, method: onFetchArticlesForFeed }
            - { name: kernel.event_listener, event: Contao\NewsBundle\Event\TransformArticleForFeedEvent, method: onTransformArticleForFeed }

    codefog_news_categories.listener.template:
        class: Codefog\NewsCategoriesBundle\EventListener\TemplateListener
        arguments:
            - "@codefog_news_categories.manager"
        tags:
            - { name: contao.hook, hook: parseArticles, method: onParseArticles }

    # Data container
    codefog_news_categories.listener.data_container.content:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\ContentListener
        arguments:
            - "@database_connection"

    codefog_news_categories.listener.data_container.news_archive:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsArchiveListener
        arguments:
            - "@codefog_news_categories.permission_checker"

    codefog_news_categories.listener.data_container.news_category:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryListener
        arguments:
            - "@database_connection"
            - "@codefog_news_categories.permission_checker"
            - "@request_stack"
            - "@?contao.slug"

    codefog_news_categories.listener.data_container.news:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsListener
        arguments:
            - "@database_connection"
            - '@Codefog\HasteBundle\DcaRelationsManager'
            - "@codefog_news_categories.permission_checker"

    codefog_news_categories.listener.data_container.settings:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\SettingsListener
        arguments:
            - "@?contao.slug.valid_characters"
